name: Log Time Job

on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write
jobs:
  log_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Logging Script
        run: |
          chmod +x log_time.sh 
          ./log_time.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add log.txt
          git commit -m "Update log file with the new timestamp" || echo "No changes to commit"
          git push
